### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by paseman** [c0redumb/yahoo_quote_download#1]
I don't have enough reputation points to leave a comment on stackoverflow, hence this note.
First, thanks for addressing the problem.
Second, I'm using Python 2.7 and replaced
import urllib.request, urllib.parse, urllib.error
with
from six.moves import urllib

when I run your test I get and error
yqd.py", line 39, in _get_cookie_crumb
    alines = f.read().decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 59021: ordinal not in range(128)

Suggestions appreciated.

**Comment by c0redumb** [comment]
Please try decode('utf-8'). Hope that helps. I will see if I can give it a try tomorrow.

**Comment by paseman** [comment]
Got past that failure for now.  Next issue is that timestamp is only in python 3 datetime

**Comment by c0redumb** [comment]
I have changed the code to use mktime(), which should be available in Python2. Check the latest revision in master, and let me know if it works.

**Comment by paseman** [comment]
Worked after I replaced
import urllib.request, urllib.parse, urllib.error
with
from six.moves import urllib
Thanks!
Also, a big benefit to your interface is the ability to download indices.
(I have been unable to do so with Google, this is why I am glad you contributed your code).
You can show this in your test stub with:
	load_quote('^DJI')

**Comment by paseman** [comment]
Whoops.  Here is what I get now intermittently.
Traceback (most recent call last):
  File "/Users/katherinepaseman/Documents/projects/DBs/Analyst/loadData/test_yqd.py", line 26, in <module>
    test()
  File "/Users/katherinepaseman/Documents/projects/DBs/Analyst/loadData/test_yqd.py", line 19, in test
    load_quote('^GDAXI')
  File "/Users/katherinepaseman/Documents/projects/DBs/Analyst/loadData/test_yqd.py", line 12, in load_quote
    print(yqd.load_yahoo_quote(ticker, '20170515', '20170517'))
  File "/Users/katherinepaseman/Documents/projects/DBs/Analyst/loadData/yahoo_quote_download/yqd.py", line 94, in load_yahoo_quote
    f = urllib.request.urlopen(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized

**Comment by c0redumb** [comment]
Let's close this issue and open an new issue with the 401 error. Thanks.
