### ISSUE TITLE
AssertionError: 1 columns passed, passed data had 7 columns

### ISSUE THREAD

**Issue by edenpan** [c0redumb/yahoo_quote_download#7]
Hi, thank you for your project that helps me a lot. But it seems has problem when i want the result output as 'dataframe'.
Here is the error log:
```
Traceback (most recent call last):  
  File "test_yqd.py", line 25, in <module>  
    test()
  File "test_yqd.py", line 18, in test
    load_quote('QCOM')
  File "test_yqd.py", line 12, in load_quote
    print(yqd.load_yahoo_quote(ticker, '20170515', '20170517',format_output = 'dataframe'))
  File "~/code/python/venv/lib/python2.7/site-packages/yahoo_quote_download-0.1-py2.7.egg/yahoo_quote_download/yqd.py", line 117, in load_yahoo_quote
    adf = pd.DataFrame.from_records(nested_alines, columns=cols)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1269, in from_records
    coerce_float=coerce_float)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 7461, in _to_arrays
    dtype=dtype)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 7540, in _list_to_arrays
    coerce_float=coerce_float)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 7598, in _convert_object_array
    con=len(content)))
AssertionError: 1 columns passed, passed data had 2 columns
```
It seems the code return dataframe may need to change to : 

```
    if format_output == 'dataframe':
		#nested_alines = [line.split(',') for line in alines[1:]]
		nested_alines = [line.split(',') for line in alines.split('\n')[1:]]
		cols = alines.split('\n')[0].split(',')
		# print(cols)
		adf = pd.DataFrame.from_records(nested_alines[:-1], columns=cols)
		return adf
```

**Comment by c0redumb** [comment]
I am not familiar with DataFrame format. It was from a contribution. Please create a pull request, and I will pull it in.

**Comment by edenpan** [comment]
Ok, i have created one.

**Comment by c0redumb** [comment]
I have just merged your pull request. Thanks for the code.
